### ISSUE TITLE
Variable names that start with "mod" will be highlighted incorrectly

### ISSUE THREAD

**Issue by bfrymire** [bscotch/stitch#72]
Variable names that start with "mod" will incorrectly highlight "mod" as if it's the modulo keyword.

![Code_xhzfcEEC54](https://github.com/bscotch/stitch/assets/20096702/59f92e10-e275-43bb-83c2-461b733218d0)

**Comment by adam-coster** [comment]
Is this true in the latest update? It was published just a little before this post.

**Comment by adam-coster** [comment]
Ah, here's the offending line:

https://github.com/bscotch/stitch/blob/07c1776b11fe8528709a91785273aafa802f7bf1/packages/vscode/syntaxes/gml.tmLanguage.yaml#L161

I just need to add `\b` around those keywords to force a word boundary, so I'll have that fixed in the next release.

Follow-up question:

Do you have semantic highlighting turned on? I would expect this issue to be hidden in that case, since semantic highlighting would override that styling.

**Comment by bfrymire** [comment]
I'm not sure how to check.

I added this to my `settings.json` just to test it out:

```json
    "editor.semanticHighlighting.enabled": true,
    "editor.semanticTokenColorCustomizations": {
        "[Dracula]": { // the theme you're using
            "enabled": true, // enable semantic highlighting
            "rules": {
                "macro": "#A600FF",
                "enum": "#FF0055",
                "enumMember": "#e97400",
                // Instance and struct variables
                "property": "#FF00A5",
                "property.static": "#FFF899",
                "variable.local": "#00FFFF",
                "parameter": "#10c3eb",
                // Built-in variables and constants
                "variable.defaultLibrary": "#58E55A",
                // Your project's global variables
                "variable.global": "#96FF4C",
                // Built-in functions
                "function.defaultLibrary": "#FFB871",
                // Asset identifiers (like sprite IDs)
                "variable.asset": "#d9760c"
            }
        }
    },
    "editor.tokenColorCustomizations": {
        // Regular (non-contextual) syntax highlighting
        "[Dracula]": {
            "comments": "#7d7d7d",
            "strings": "#FFFF00",
            "numbers": "#FFFF00",
            // etc.
        }
    }
```

After making the change, I still see the highlighting issue.

**Comment by adam-coster** [comment]
Huh. Does all of the rest of the highlighting work correctly? E.g with semantic highlighting enabled do you see all of the different colors you expect?

I just published 0.22.3, which fixes those patterns so that they shouldn't highlight improperly anymore. Once you get the update, please let me know if it's resolved!

**Comment by adam-coster** [comment]
I'm assuming this is resolved since I cannot replicate it. Closing.
